<?php
$checkoutData = $block->getCheckoutData();
?>

<div class="checkout-success">
    <script>
        require(['jquery'], function($){
            var sipScript = document.createElement('script');
            sipScript.setAttribute("class",             "mcafeesecure-track-conversion");
            sipScript.setAttribute("type",              "text/javascript");
            sipScript.setAttribute("data-type",         "purchase");
            sipScript.setAttribute("data-email",        "<?php echo __($block->escapeUrl($checkoutData['email'])) ?>");
            sipScript.setAttribute("data-firstname",    "<?php echo __($block->escapeUrl($checkoutData['firstname'])) ?>");
            sipScript.setAttribute("data-lastname",     "<?php echo __($block->escapeUrl($checkoutData['lastname'])) ?>");
            sipScript.setAttribute("data-amount",       "<?php echo __($block->escapeUrl($checkoutData['amount'])) ?>");
            sipScript.setAttribute("data-state",        "<?php echo __($block->escapeUrl($checkoutData['region'])) ?>");
            sipScript.setAttribute("data-country",      "<?php echo __($block->escapeUrl($checkoutData['country'])) ?>");
            sipScript.setAttribute("data-orderid",      "<?php echo __($block->escapeUrl($checkoutData['orderid'])) ?>");
            sipScript.setAttribute("src",               "https://cdn.ywxi.net/js/conversion.js");
            document.getElementsByTagName("head")[0].appendChild(sipScript);
        });
    </script>
</div>