<?php

$host = urlencode($block->getHost());
$email = urlencode($block->getUserEmail());
$affiliate = "265987";
$partner = "magento";
$source = "magento";
$endpoint = "https://trustedsite.com";

?>

<div id="iframe-container">
</div>

<script>

    require(['jquery'],function($){

        $(document).ready(function () {
            loadPage();
        });

        function loadPage() {
            var $iframeContainer = $('#iframe-container');

            var $iframe = $("<iframe></iframe>");
            $iframe.attr({
                "width": "100%",
                "height": "800px",
                "seamless": true,
                "scrolling": "yes",
                "frameborder": "0"
            });

            $iframe.attr("src", "<?php echo $endpoint; ?>/app/partner2/signup?&aff=<?php echo $affiliate; ?>&source=<?php echo $partner; ?>&partner=<?php echo $partner; ?>&email=<?php echo $email; ?>&host=<?php echo $host; ?>"); 
            $iframe.attr("style", "border: 1px solid rgba(0, 0, 0, 0.12);")
            $iframeContainer.html($iframe);
        }
    });
</script>
